### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by klauskpm** [klauskpm/cz-simple-changelog#6]
# Description
In README.md, add the following badges before the description and after the title:
```
Status:
[![npm version](https://img.shields.io/npm/v/cz-simple-changelog.svg?style=flat-square)](https://www.npmjs.org/package/cz-simple-changelog)
[![npm downloads](https://img.shields.io/npm/dm/cz-simple-changelog.svg?style=flat-square)](http://npm-stat.com/charts.html?package=cz-simple-changelog&from=2015-08-01)
```

## 🥇 Call dibs 
Say you will do this issue. I don't need to give you permission, but, if someone called dibs first and you send your PR after that, I will tag your PR as invalid.

Respect the dibs 👊

**Comment by dlmarrero** [comment]
dibs

**Comment by klauskpm** [comment]
Thank you for your contribution @dlmarrero ! Have a happy Hacktoberfest!
